name: 'Upload SPA to Azure Blob'
description: 'Deploys a frontend to Azure Blob and activates the index.html file at last'
author: 'CoreHelpers Project'
branding:
  icon: 'upload-cloud'
  color: 'purple'
inputs:
  connectionstring: 
    required: true
    type: string  
  container:
    required: true
    type: string  
  source:
    required: true
    type: string  
    
runs:
  using: "composite"
  steps:    
    - name: Create Upload Workspace
      id: uploadworkspace
      shell: bash
      run: |
        GUID=$(uuidgen)
        UNIQUE_DIR="${RUNNER_TEMP}/${GUID}"
        mkdir -p "$UNIQUE_DIR"
        echo "Created: $UNIQUE_DIR"
        echo "upload_workspace=$UNIQUE_DIR" >> "$GITHUB_OUTPUT"
        
    - name: Prepare upload without index.html
      shell: bash
      run: |
        mkdir ${{ steps.uploadworkspace.outputs.upload_workspace }}
        rsync -av --exclude 'index.html' '${{ inputs.source }}' "${{ steps.uploadworkspace.outputs.upload_workspace }}/"

    - name: Upload all without index.html to Azure Blob (pre-stage)
      uses: azure/cli@v2
      with:
        inlineScript: |      
          az storage blob upload-batch \
            --connection-string '${{ inputs.connectionstring }}' \
            --overwrite  \
            --destination '${{ inputs.container }}' \
            --source ${{ steps.uploadworkspace.outputs.upload_workspace }} 

    - name: Upload the index.html to Azure Blob (activation)
      uses: azure/cli@v2      
      with:
        inlineScript: |      
          az storage blob upload \
            --connection-string '${{ inputs.connectionstring }}' \
            --container-name '${{ inputs.container }}' \
            --file ${{ inputs.source }}/index.html \
            --name index.html \
            --overwrite \
            --content-type text/html \
            --content-cache-control "no-cache"
